name: "Build and Deploy"
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build Package
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
        
    - name: Pack
      #run: dotnet pack TestLib --configuration Release -o finalpackage --no-build
      
      run: dotnet pack --configuration Release
      
    - name: Add source
      run: dotnet nuget add source --username vvalusa --password {{ seecrets.github_token }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vvalusa/index.json"

